services:
  markme-backend: 
    build: ./Backend
    ports:
      - "4000:4000"
    networks:
      - Mark-Me
    environment:
      - SUPABASEKEY= ""
    depends_on:
      - mongo

  markme-frontend:
    build: ./Frontend
    ports:
      - "5174:5174"
    networks:
      - Mark-Me


  employee-panel:
    build: ./EmployeePanel
    ports:
      - "5173:5173"
    networks:
      - Mark-Me

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - Mark-Me

networks:
  Mark-Me:
    driver: bridge      